/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.janelaprogramacao;

/**
 *
 * @author HP
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RESULTADO = new javax.swing.JLabel();
        PYTHON = new javax.swing.JButton();
        JAVA = new javax.swing.JButton();
        PHP = new javax.swing.JButton();
        KOTLIN = new javax.swing.JButton();
        JAVASCRIPT = new javax.swing.JButton();
        TYPESCRIPT = new javax.swing.JButton();
        RUBY = new javax.swing.JButton();
        GO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("JANELA PROGRAMAÇÃO");

        RESULTADO.setText("RESULTADO:");

        PYTHON.setText("PYTHON");
        PYTHON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PYTHONActionPerformed(evt);
            }
        });

        JAVA.setText("JAVA");
        JAVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAVAActionPerformed(evt);
            }
        });

        PHP.setText("PHP");
        PHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PHPActionPerformed(evt);
            }
        });

        KOTLIN.setText("KOTLIN");
        KOTLIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KOTLINActionPerformed(evt);
            }
        });

        JAVASCRIPT.setText("JAVASCRIPT");
        JAVASCRIPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAVASCRIPTActionPerformed(evt);
            }
        });

        TYPESCRIPT.setText("TYPESCRIPT");
        TYPESCRIPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TYPESCRIPTActionPerformed(evt);
            }
        });

        RUBY.setText("RUBY");
        RUBY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RUBYActionPerformed(evt);
            }
        });

        GO.setText("GO");
        GO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RESULTADO, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(PYTHON, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                        .addComponent(JAVA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(KOTLIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(PHP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JAVASCRIPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TYPESCRIPT, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(RUBY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(GO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(39, 39, 39)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(RESULTADO)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PYTHON)
                    .addComponent(JAVASCRIPT))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JAVA)
                    .addComponent(TYPESCRIPT))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PHP)
                    .addComponent(RUBY))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KOTLIN)
                    .addComponent(GO))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JAVASCRIPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAVASCRIPTActionPerformed
        RESULTADO.setText("VOCÊ CRICOU NO JAVASCRIPT!");
    }//GEN-LAST:event_JAVASCRIPTActionPerformed

    private void PYTHONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PYTHONActionPerformed
        RESULTADO.setText("VOCÊ CRICOU NO PYTHON!");
    }//GEN-LAST:event_PYTHONActionPerformed

    private void JAVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAVAActionPerformed
        RESULTADO.setText("VOCÊ CRICOU NO JAVA!");
    }//GEN-LAST:event_JAVAActionPerformed

    private void PHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PHPActionPerformed
       RESULTADO.setText("VOCÊ CRICOU NO PHP!");
    }//GEN-LAST:event_PHPActionPerformed

    private void KOTLINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KOTLINActionPerformed
       RESULTADO.setText("VOCÊ CRICOU NO KOTLIN!");
    }//GEN-LAST:event_KOTLINActionPerformed

    private void TYPESCRIPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TYPESCRIPTActionPerformed
        RESULTADO.setText("VOCÊ CRICOU NO TYPESCRIPT!");
    }//GEN-LAST:event_TYPESCRIPTActionPerformed

    private void RUBYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RUBYActionPerformed
        RESULTADO.setText("VOCÊ CRICOU NO RUBY!");
    }//GEN-LAST:event_RUBYActionPerformed

    private void GOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GOActionPerformed
       RESULTADO.setText("VOCÊ CRICOU NO GO!");
    }//GEN-LAST:event_GOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GO;
    private javax.swing.JButton JAVA;
    private javax.swing.JButton JAVASCRIPT;
    private javax.swing.JButton KOTLIN;
    private javax.swing.JButton PHP;
    private javax.swing.JButton PYTHON;
    private javax.swing.JLabel RESULTADO;
    private javax.swing.JButton RUBY;
    private javax.swing.JButton TYPESCRIPT;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
